name: Nextflow Stub Runs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  stub-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [
          'test-diann.config',
          'test-cascadia.config',
          'test-encyclopedia-narrow-gpf.config',
          'test-encyclopedia-wide-only.config',
          'test-diann-pdc.config',
          'test-msconvert-only-pdc.config',
          'test-msconvert-only-local.config'
        ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run (${{ matrix.config }})
      run: |
        echo "Installing Nextflow:"
        export NXF_VER=24.04.4   # Specify nextflow version. Currently there is a bug in 24.10.0
        curl -s https://get.nextflow.io | bash
        chmod +x nextflow
        echo "Running Nextflow stub with config: ${{ matrix.config }}"
        ./nextflow run . -stub-run -c test-resources/${{ matrix.config }}
